<?php
/**
 * Cruise data for Ha Long Bay cruises
 * Shared between cruises.php, cruise_details.php, and index.php
 */

$cruises_data = [
  'ambassador' => [
    'id'           => 'ambassador',
    'name'         => 'Ambassador Cruise',
    'class'        => 5,
    'image'        => 'images/cruises/ambassador.jpg',
    'gallery'      => ['images/cruises/ambassador.jpg'],
    'desc_vi'      => 'Du thuyền sang trọng bậc nhất vịnh Hạ Long với 46 cabin, ẩm thực Michelin Star do bếp trưởng John Burton-Race thiết kế. Hành trình qua hang Sửng Sốt, đảo Ti Tốp và làng chài Cửa Vạn.',
    'desc_en'      => 'The most luxurious cruise on Ha Long Bay with 46 cabins and Michelin Star cuisine by Chef John Burton-Race. Itinerary includes Sung Sot Cave, Ti Top Island and Cua Van fishing village.',
    'long_desc_vi' => 'Ambassador Cruise là du thuyền 5 sao hàng đầu tại vịnh Hạ Long, nổi tiếng với trải nghiệm ẩm thực đẳng cấp quốc tế được thiết kế bởi bếp trưởng Michelin Star — John Burton-Race. Với 46 cabin sang trọng, tàu sở hữu bể Jacuzzi ngoài trời duy nhất trên vịnh, sân thượng 360 độ panorama, phòng Piano Lounge và cầu kính Sky Walk độc đáo. Hành trình 2 ngày 1 đêm đưa du khách khám phá hang Sửng Sốt — hang động lớn nhất vịnh Hạ Long, chinh phục đảo Ti Tốp với tầm nhìn toàn cảnh vịnh, và trải nghiệm thuyền tre xuyên qua làng chài Cửa Vạn — di sản văn hóa phi vật thể cần bảo tồn.',
    'long_desc_en' => 'Ambassador Cruise is a leading 5-star cruise in Ha Long Bay, renowned for its world-class culinary experience designed by Michelin Star Chef John Burton-Race. With 46 luxury cabins, the vessel features the only outdoor Jacuzzi on the bay, a 360-degree panoramic sundeck, Piano Lounge, and the unique Sky Walk glass bridge. The 2-day-1-night itinerary takes guests to explore Sung Sot Cave — the largest cave in Ha Long Bay, conquer Ti Top Island for panoramic bay views, and experience bamboo boats through Cua Van Fishing Village — a cultural heritage site.',
    'price_from'   => '3.800.000',
    'cabin_count'  => 46,
    'year_launched' => 2019,
    'route_vi'     => 'Vịnh Hạ Long',
    'route_en'     => 'Ha Long Bay',
    'highlights'   => ['Ẩm thực Michelin', 'Hang Sửng Sốt', 'Jacuzzi ngoài trời', 'Kayak', 'Câu mực đêm', 'Cầu kính Sky Walk', 'Piano Lounge'],
    'highlights_en' => ['Michelin cuisine', 'Sung Sot Cave', 'Outdoor Jacuzzi', 'Kayaking', 'Night squid fishing', 'Sky Walk glass bridge', 'Piano Lounge'],
    'rating'       => 4.7,
    'reviews'      => 2850,
    'color'        => '#C8A951',
    'itinerary_vi' => [
      'day1' => [
        'title' => 'Ngày 1: Hạ Long — Hang Sửng Sốt — Đảo Ti Tốp',
        'items' => [
          '11:30 — Nhận phòng tại bến tàu, welcome drink & giới thiệu an toàn',
          '12:30 — Ăn trưa buffet hải sản tươi sống trên tàu',
          '14:00 — Tham quan hang Sửng Sốt — hang động lớn nhất vịnh',
          '15:30 — Tắm biển & leo núi đảo Ti Tốp, ngắm toàn cảnh vịnh',
          '17:00 — Trở về tàu, thư giãn tại Jacuzzi ngoài trời',
          '18:00 — Lớp nấu ăn Việt Nam trên sundeck',
          '19:30 — Gala dinner với thực đơn Michelin Star',
          '21:00 — Câu mực đêm, thưởng thức nhạc sống Piano Lounge',
        ],
      ],
      'day2' => [
        'title' => 'Ngày 2: Làng chài Cửa Vạn — Trở về',
        'items' => [
          '06:30 — Tai Chi buổi sáng trên sundeck',
          '07:00 — Ăn sáng buffet phong cách quốc tế',
          '08:00 — Thuyền tre khám phá làng chài Cửa Vạn',
          '09:30 — Trả phòng, thanh toán dịch vụ',
          '10:00 — Brunch nhẹ, ngắm cảnh vịnh Hạ Long',
          '11:00 — Cập bến, kết thúc hành trình',
        ],
      ],
    ],
    'itinerary_en' => [
      'day1' => [
        'title' => 'Day 1: Ha Long — Sung Sot Cave — Ti Top Island',
        'items' => [
          '11:30 AM — Check-in at the pier, welcome drink & safety briefing',
          '12:30 PM — Fresh seafood buffet lunch onboard',
          '2:00 PM — Visit Sung Sot Cave — the largest cave in the bay',
          '3:30 PM — Swimming & hiking at Ti Top Island, panoramic bay views',
          '5:00 PM — Return to cruise, relax at outdoor Jacuzzi',
          '6:00 PM — Vietnamese cooking class on the sundeck',
          '7:30 PM — Gala dinner with Michelin Star menu',
          '9:00 PM — Night squid fishing, live music at Piano Lounge',
        ],
      ],
      'day2' => [
        'title' => 'Day 2: Cua Van Fishing Village — Return',
        'items' => [
          '6:30 AM — Morning Tai Chi on the sundeck',
          '7:00 AM — International-style breakfast buffet',
          '8:00 AM — Bamboo boat ride through Cua Van Fishing Village',
          '9:30 AM — Check out and settle bills',
          '10:00 AM — Light brunch while cruising Ha Long Bay',
          '11:00 AM — Disembark, end of journey',
        ],
      ],
    ],
    'cabins_vi' => [
      ['name' => 'Deluxe Balcony', 'size' => '25m²', 'bed' => 'Giường đôi / 2 giường đơn', 'price' => '3.800.000', 'desc' => 'Cabin tiêu chuẩn với ban công riêng, cửa kính toàn cảnh vịnh'],
      ['name' => 'Executive Suite', 'size' => '38m²', 'bed' => 'Giường King', 'price' => '5.200.000', 'desc' => 'Suite cao cấp với phòng khách riêng, bồn tắm view biển'],
      ['name' => 'Ambassador Suite', 'size' => '52m²', 'bed' => 'Giường King', 'price' => '7.500.000', 'desc' => 'Suite đẳng cấp nhất, ban công rộng, dịch vụ butler riêng'],
    ],
    'cabins_en' => [
      ['name' => 'Deluxe Balcony', 'size' => '25m²', 'bed' => 'Double / Twin beds', 'price' => '3,800,000', 'desc' => 'Standard cabin with private balcony and panoramic bay windows'],
      ['name' => 'Executive Suite', 'size' => '38m²', 'bed' => 'King bed', 'price' => '5,200,000', 'desc' => 'Premium suite with separate living area and sea-view bathtub'],
      ['name' => 'Ambassador Suite', 'size' => '52m²', 'bed' => 'King bed', 'price' => '7,500,000', 'desc' => 'Top-tier suite with spacious balcony and private butler'],
    ],
    'amenities' => ['Wi-Fi', 'Jacuzzi', 'Spa', 'Piano Lounge', 'Sky Walk', 'Nhà hàng', 'Bar', 'Sundeck 360°', 'Phòng Gym'],
    'amenities_en' => ['Wi-Fi', 'Jacuzzi', 'Spa', 'Piano Lounge', 'Sky Walk', 'Restaurant', 'Bar', '360° Sundeck', 'Gym'],
  ],

  'paradise' => [
    'id'           => 'paradise',
    'name'         => 'Paradise Elegance',
    'class'        => 5,
    'image'        => 'images/cruises/paradise.jpg',
    'gallery'      => ['images/cruises/paradise.jpg'],
    'desc_vi'      => 'Kiệt tác du thuyền kết hợp phong cách hiện đại và truyền thống Việt Nam. Nổi bật với piano bar, trung tâm spa & wellness và dịch vụ butler riêng cho từng cabin.',
    'desc_en'      => 'A masterpiece cruise blending modern and traditional Vietnamese style. Features a piano bar, spa & wellness center and private butler service for each cabin.',
    'long_desc_vi' => 'Paradise Elegance là niềm tự hào của đội tàu Paradise Vietnam — du thuyền lớn nhất, thoải mái nhất và sang trọng nhất vịnh Hạ Long với 31 cabin. Được thiết kế hài hòa giữa phong cách hiện đại và nét truyền thống Việt Nam, tàu sở hữu quầy Piano Bar sang trọng, trung tâm Spa & Wellness đẳng cấp, và dịch vụ Butler riêng biệt. Du khách sẽ được thưởng thức ẩm thực Việt — Á — Âu tinh tế, tham gia lớp nấu ăn trên sundeck, tập Tai Chi buổi sáng giữa vịnh, và khám phá hang Sửng Sốt, đảo Ti Tốp, trại nuôi ngọc trai Tung Sâu.',
    'long_desc_en' => 'Paradise Elegance is the pride of the Paradise Vietnam fleet — the largest, most comfortable and luxurious cruise in Ha Long Bay with 31 cabins. Harmoniously designed between modern style and Vietnamese tradition, the vessel features an elegant Piano Bar, premium Spa & Wellness center, and exclusive Butler service. Guests enjoy refined Vietnamese-Asian-European cuisine, cooking classes on the sundeck, morning Tai Chi in the bay, and explore Sung Sot Cave, Ti Top Island, and Tung Sau Pearl Farm.',
    'price_from'   => '3.600.000',
    'cabin_count'  => 31,
    'year_launched' => 2017,
    'route_vi'     => 'Vịnh Hạ Long',
    'route_en'     => 'Ha Long Bay',
    'highlights'   => ['Piano bar', 'Spa & Wellness', 'Butler riêng', 'Tai Chi sáng', 'Làng nổi Cửa Vạn', 'Trại ngọc trai', 'Lớp nấu ăn'],
    'highlights_en' => ['Piano bar', 'Spa & Wellness', 'Private butler', 'Morning Tai Chi', 'Cua Van floating village', 'Pearl farm', 'Cooking class'],
    'rating'       => 4.8,
    'reviews'      => 3500,
    'color'        => '#8B5CF6',
    'itinerary_vi' => [
      'day1' => [
        'title' => 'Ngày 1: Hạ Long — Trại ngọc trai — Hang Sửng Sốt',
        'items' => [
          '12:00 — Nhận phòng, cocktail chào mừng',
          '12:30 — Ăn trưa set menu Việt — Á — Âu',
          '14:30 — Chèo kayak tại trại ngọc trai Tung Sâu',
          '16:00 — Tham quan hang Sửng Sốt',
          '17:30 — Trở về tàu, thư giãn tại spa',
          '18:30 — Lớp nấu ăn trên sundeck với bếp trưởng',
          '19:30 — Dinner đặc biệt, piano live music',
          '21:00 — Câu mực đêm hoặc xem phim trên tàu',
        ],
      ],
      'day2' => [
        'title' => 'Ngày 2: Đảo Ti Tốp — Trở về',
        'items' => [
          '06:00 — Tai Chi buổi sáng giữa vịnh',
          '07:00 — Ăn sáng buffet',
          '08:00 — Tắm biển & trekking đảo Ti Tốp',
          '09:30 — Trả phòng',
          '10:00 — Brunch, ngắm cảnh khi tàu về bến',
          '11:30 — Cập bến, kết thúc hành trình',
        ],
      ],
    ],
    'itinerary_en' => [
      'day1' => [
        'title' => 'Day 1: Ha Long — Pearl Farm — Sung Sot Cave',
        'items' => [
          '12:00 PM — Check-in, welcome cocktail',
          '12:30 PM — Vietnamese-Asian-European set lunch',
          '2:30 PM — Kayaking at Tung Sau Pearl Farm',
          '4:00 PM — Visit Sung Sot Cave',
          '5:30 PM — Return to cruise, relax at spa',
          '6:30 PM — Cooking class on sundeck with the chef',
          '7:30 PM — Special dinner with live piano music',
          '9:00 PM — Night squid fishing or movie night',
        ],
      ],
      'day2' => [
        'title' => 'Day 2: Ti Top Island — Return',
        'items' => [
          '6:00 AM — Morning Tai Chi on the bay',
          '7:00 AM — Breakfast buffet',
          '8:00 AM — Swimming & trekking at Ti Top Island',
          '9:30 AM — Check out',
          '10:00 AM — Brunch, scenic cruising back',
          '11:30 AM — Disembark, end of journey',
        ],
      ],
    ],
    'cabins_vi' => [
      ['name' => 'Deluxe Balcony', 'size' => '25m²', 'bed' => 'Giường đôi / 2 giường đơn', 'price' => '3.600.000', 'desc' => 'Cabin tiêu chuẩn ban công riêng, view vịnh'],
      ['name' => 'Executive Balcony', 'size' => '25m²', 'bed' => 'Giường đôi', 'price' => '4.200.000', 'desc' => 'Tầng trên, tầm nhìn thoáng đãng hơn'],
      ['name' => 'Elegance Suite', 'size' => '35m²', 'bed' => 'Giường King', 'price' => '5.800.000', 'desc' => 'Suite rộng rãi với phòng khách và bồn tắm view biển'],
      ['name' => "Captain's View Terrace", 'size' => '35m²', 'bed' => 'Giường King', 'price' => '6.500.000', 'desc' => 'Suite đỉnh cao với sân thượng riêng, tầm nhìn 180°'],
    ],
    'cabins_en' => [
      ['name' => 'Deluxe Balcony', 'size' => '25m²', 'bed' => 'Double / Twin beds', 'price' => '3,600,000', 'desc' => 'Standard cabin with private balcony and bay view'],
      ['name' => 'Executive Balcony', 'size' => '25m²', 'bed' => 'Double bed', 'price' => '4,200,000', 'desc' => 'Upper deck with wider panoramic views'],
      ['name' => 'Elegance Suite', 'size' => '35m²', 'bed' => 'King bed', 'price' => '5,800,000', 'desc' => 'Spacious suite with living area and sea-view bathtub'],
      ['name' => "Captain's View Terrace", 'size' => '35m²', 'bed' => 'King bed', 'price' => '6,500,000', 'desc' => 'Top-tier suite with private terrace and 180° views'],
    ],
    'amenities' => ['Wi-Fi', 'Spa & Wellness', 'Piano Bar', 'Butler', 'Nhà hàng', 'Sundeck', 'Thư viện'],
    'amenities_en' => ['Wi-Fi', 'Spa & Wellness', 'Piano Bar', 'Butler', 'Restaurant', 'Sundeck', 'Library'],
  ],

  'stellar' => [
    'id'           => 'stellar',
    'name'         => 'Stellar of the Seas',
    'class'        => 6,
    'image'        => 'images/cruises/stellar.jpg',
    'gallery'      => ['images/cruises/stellar.jpg'],
    'desc_vi'      => 'Du thuyền 6 sao đẳng cấp với hồ bơi ngoài trời lớn nhất vịnh Hạ Long (50m²), sân mini golf, hầm rượu vang và phòng xì gà — trải nghiệm nghỉ dưỡng đỉnh cao trên mặt nước.',
    'desc_en'      => 'A 6-star cruise featuring the largest outdoor pool in Ha Long Bay (50m²), mini golf, wine cellar and cigar lounge — the ultimate luxury experience on water.',
    'long_desc_vi' => 'Stellar of the Seas thuộc Aclass Cruise Group là du thuyền 6 sao đầu tiên và duy nhất tại vịnh Hạ Long, định nghĩa lại tiêu chuẩn nghỉ dưỡng trên mặt nước. Với 22 cabin siêu sang, tàu sở hữu hồ bơi ngoài trời lớn nhất vịnh (50m²), sân mini golf, hầm rượu vang Pháp, phòng xì gà Cuba, bar 360° và nhà hàng fine-dining 60 chỗ. Hành trình khám phá vịnh Lan Hạ — phiên bản hoang sơ và yên bình hơn của vịnh Hạ Long, với hang Sáng Tối, khu vực Ao Ếch, và bãi tắm riêng giữa những vách đá vôi kỳ vĩ.',
    'long_desc_en' => 'Stellar of the Seas by Aclass Cruise Group is the first and only 6-star cruise in Ha Long Bay, redefining the standard of luxury on water. With 22 premium cabins, the vessel features the largest outdoor pool in the bay (50m²), mini golf course, French wine cellar, Cuban cigar lounge, 360° bar, and a 60-seat fine-dining restaurant. The itinerary explores Lan Ha Bay — a more pristine and peaceful version of Ha Long Bay, featuring Dark & Bright Cave, Ao Ech area, and private beaches among majestic limestone cliffs.',
    'price_from'   => '4.500.000',
    'cabin_count'  => 22,
    'year_launched' => 2018,
    'route_vi'     => 'Vịnh Lan Hạ',
    'route_en'     => 'Lan Ha Bay',
    'highlights'   => ['Hồ bơi 50m²', 'Mini golf', 'Hầm rượu vang', 'Phòng xì gà', 'Spa cao cấp', 'Bar 360°', 'Fine dining'],
    'highlights_en' => ['50m² pool', 'Mini golf', 'Wine cellar', 'Cigar lounge', 'Premium spa', '360° bar', 'Fine dining'],
    'rating'       => 4.9,
    'reviews'      => 742,
    'color'        => '#D4AF37',
    'itinerary_vi' => [
      'day1' => [
        'title' => 'Ngày 1: Vịnh Lan Hạ — Hang Sáng Tối — Ao Ếch',
        'items' => [
          '11:30 — Nhận phòng tại Tuần Châu Marina, welcome champagne',
          '12:30 — Fine dining lunch trên tàu',
          '14:30 — Thuyền tre khám phá hang Sáng Tối',
          '16:00 — Chèo kayak khu vực Ao Ếch',
          '17:00 — Tắm biển tại bãi riêng',
          '18:00 — Cocktail trên bar 360°, ngắm hoàng hôn',
          '19:30 — BBQ dinner trên sundeck',
          '21:00 — Câu mực, thưởng thức rượu vang tại hầm rượu',
        ],
      ],
      'day2' => [
        'title' => 'Ngày 2: Bơi sáng — Trở về',
        'items' => [
          '06:00 — Tai Chi buổi sáng bên hồ bơi',
          '07:00 — Ăn sáng buffet cao cấp',
          '08:00 — Bơi tại hồ bơi ngoài trời 50m²',
          '09:00 — Mini golf trên sundeck',
          '09:30 — Trả phòng',
          '10:30 — Brunch nhẹ khi tàu về bến',
          '11:30 — Cập bến Tuần Châu',
        ],
      ],
    ],
    'itinerary_en' => [
      'day1' => [
        'title' => 'Day 1: Lan Ha Bay — Dark & Bright Cave — Ao Ech',
        'items' => [
          '11:30 AM — Check-in at Tuan Chau Marina, welcome champagne',
          '12:30 PM — Fine dining lunch onboard',
          '2:30 PM — Bamboo boat through Dark & Bright Cave',
          '4:00 PM — Kayaking in Ao Ech area',
          '5:00 PM — Swimming at private beach',
          '6:00 PM — Cocktails at 360° bar, sunset viewing',
          '7:30 PM — BBQ dinner on sundeck',
          '9:00 PM — Squid fishing, wine tasting at the cellar',
        ],
      ],
      'day2' => [
        'title' => 'Day 2: Morning Swim — Return',
        'items' => [
          '6:00 AM — Morning Tai Chi by the pool',
          '7:00 AM — Premium breakfast buffet',
          '8:00 AM — Swimming in the 50m² outdoor pool',
          '9:00 AM — Mini golf on the sundeck',
          '9:30 AM — Check out',
          '10:30 AM — Light brunch while cruising back',
          '11:30 AM — Disembark at Tuan Chau',
        ],
      ],
    ],
    'cabins_vi' => [
      ['name' => 'Stellar Suite', 'size' => '36m²', 'bed' => 'Giường King', 'price' => '4.500.000', 'desc' => 'Suite sang trọng với ban công riêng view vịnh Lan Hạ'],
      ['name' => 'Captain Suite', 'size' => '46m²', 'bed' => 'Giường King', 'price' => '6.800.000', 'desc' => 'Suite cao cấp với phòng khách, bồn tắm jacuzzi riêng'],
      ['name' => 'Presidential Suite', 'size' => '60m²', 'bed' => 'Giường King', 'price' => '9.500.000', 'desc' => 'Suite tổng thống, sân thượng riêng, dịch vụ VIP'],
    ],
    'cabins_en' => [
      ['name' => 'Stellar Suite', 'size' => '36m²', 'bed' => 'King bed', 'price' => '4,500,000', 'desc' => 'Luxury suite with private balcony and Lan Ha Bay view'],
      ['name' => 'Captain Suite', 'size' => '46m²', 'bed' => 'King bed', 'price' => '6,800,000', 'desc' => 'Premium suite with living room and private jacuzzi bathtub'],
      ['name' => 'Presidential Suite', 'size' => '60m²', 'bed' => 'King bed', 'price' => '9,500,000', 'desc' => 'Presidential suite with private terrace and VIP service'],
    ],
    'amenities' => ['Hồ bơi 50m²', 'Mini Golf', 'Hầm rượu', 'Phòng xì gà', 'Spa', 'Gym', 'Bar 360°', 'Wi-Fi'],
    'amenities_en' => ['50m² Pool', 'Mini Golf', 'Wine Cellar', 'Cigar Lounge', 'Spa', 'Gym', '360° Bar', 'Wi-Fi'],
  ],

  'athena' => [
    'id'           => 'athena',
    'name'         => 'Athena Luxury',
    'class'        => 5,
    'image'        => 'images/cruises/athena.jpg',
    'gallery'      => ['images/cruises/athena.jpg'],
    'desc_vi'      => 'Du thuyền 5 sao thiết kế hiện đại 3 tầng với 21 cabin, sundeck mở cùng open bar và lounge cà phê. Lựa chọn hoàn hảo cho những ai yêu thích sự tinh tế và riêng tư.',
    'desc_en'      => 'A modern 3-deck 5-star cruise with 21 cabins, open sundeck bar and coffee lounge. Perfect for those seeking elegance and privacy.',
    'long_desc_vi' => 'Athena Luxury là du thuyền 5 sao với thiết kế hiện đại 3 tầng, mang đến 21 cabin tiện nghi sang trọng. Điểm nhấn của tàu là sundeck mở thoáng đãng với open bar và café lounge — nơi hoàn hảo để ngắm cảnh vịnh Hạ Long bất kỳ lúc nào. Với phong cách phục vụ tinh tế và không gian riêng tư, Athena Luxury là lựa chọn lý tưởng cho các cặp đôi, gia đình nhỏ và du khách yêu thích sự yên tĩnh. Hành trình khám phá các hang động nổi tiếng và chèo kayak giữa thiên nhiên hoang sơ.',
    'long_desc_en' => 'Athena Luxury is a 5-star cruise with a modern 3-deck design, offering 21 well-appointed luxury cabins. The highlight is the open sundeck with an open bar and café lounge — the perfect spot to enjoy Ha Long Bay views anytime. With refined service and private spaces, Athena Luxury is ideal for couples, small families, and travelers seeking tranquility. The itinerary explores famous caves and kayaking through pristine nature.',
    'price_from'   => '2.800.000',
    'cabin_count'  => 21,
    'year_launched' => 2018,
    'route_vi'     => 'Vịnh Hạ Long',
    'route_en'     => 'Ha Long Bay',
    'highlights'   => ['Sundeck open bar', 'Café lounge', 'Sauna & Spa', 'Hang động', 'Kayak', 'Câu mực đêm', 'Nấu ăn'],
    'highlights_en' => ['Sundeck open bar', 'Café lounge', 'Sauna & Spa', 'Cave tour', 'Kayaking', 'Night squid fishing', 'Cooking class'],
    'rating'       => 4.6,
    'reviews'      => 1280,
    'color'        => '#2D6A4F',
    'itinerary_vi' => [
      'day1' => [
        'title' => 'Ngày 1: Hạ Long — Hang Luồn — Bãi tắm',
        'items' => [
          '12:00 — Nhận phòng, welcome drink tại café lounge',
          '12:30 — Ăn trưa set menu trên tàu',
          '14:30 — Tham quan hang Luồn bằng thuyền tre',
          '16:00 — Tắm biển tại bãi riêng',
          '17:00 — Thư giãn tại spa & sauna',
          '18:00 — Happy hour tại sundeck open bar',
          '19:30 — Dinner, thưởng thức đồ uống',
          '21:00 — Câu mực đêm, karaoke',
        ],
      ],
      'day2' => [
        'title' => 'Ngày 2: Kayak — Trở về',
        'items' => [
          '06:30 — Tai Chi buổi sáng',
          '07:00 — Ăn sáng buffet',
          '08:00 — Chèo kayak khám phá vịnh',
          '09:30 — Trả phòng',
          '10:30 — Brunch, ngắm cảnh',
          '11:00 — Cập bến',
        ],
      ],
    ],
    'itinerary_en' => [
      'day1' => [
        'title' => 'Day 1: Ha Long — Luon Cave — Beach',
        'items' => [
          '12:00 PM — Check-in, welcome drink at café lounge',
          '12:30 PM — Set lunch onboard',
          '2:30 PM — Visit Luon Cave by bamboo boat',
          '4:00 PM — Swimming at private beach',
          '5:00 PM — Relax at spa & sauna',
          '6:00 PM — Happy hour at sundeck open bar',
          '7:30 PM — Dinner with drinks',
          '9:00 PM — Night squid fishing, karaoke',
        ],
      ],
      'day2' => [
        'title' => 'Day 2: Kayaking — Return',
        'items' => [
          '6:30 AM — Morning Tai Chi',
          '7:00 AM — Breakfast buffet',
          '8:00 AM — Kayaking to explore the bay',
          '9:30 AM — Check out',
          '10:30 AM — Brunch, scenic views',
          '11:00 AM — Disembark',
        ],
      ],
    ],
    'cabins_vi' => [
      ['name' => 'Deluxe Ocean View', 'size' => '22m²', 'bed' => 'Giường đôi / 2 giường đơn', 'price' => '2.800.000', 'desc' => 'Cabin cửa sổ lớn, view biển'],
      ['name' => 'Premium Balcony', 'size' => '28m²', 'bed' => 'Giường King', 'price' => '3.800.000', 'desc' => 'Cabin ban công riêng, không gian rộng rãi'],
      ['name' => 'Athena Suite', 'size' => '40m²', 'bed' => 'Giường King', 'price' => '5.200.000', 'desc' => 'Suite cao cấp với phòng khách riêng biệt'],
    ],
    'cabins_en' => [
      ['name' => 'Deluxe Ocean View', 'size' => '22m²', 'bed' => 'Double / Twin beds', 'price' => '2,800,000', 'desc' => 'Large window cabin with sea view'],
      ['name' => 'Premium Balcony', 'size' => '28m²', 'bed' => 'King bed', 'price' => '3,800,000', 'desc' => 'Private balcony cabin with spacious layout'],
      ['name' => 'Athena Suite', 'size' => '40m²', 'bed' => 'King bed', 'price' => '5,200,000', 'desc' => 'Premium suite with separate living area'],
    ],
    'amenities' => ['Wi-Fi', 'Spa & Sauna', 'Open Bar', 'Café Lounge', 'Nhà hàng', 'Sundeck', 'Karaoke'],
    'amenities_en' => ['Wi-Fi', 'Spa & Sauna', 'Open Bar', 'Café Lounge', 'Restaurant', 'Sundeck', 'Karaoke'],
  ],

  'dragon-legend' => [
    'id'           => 'dragon-legend',
    'name'         => 'Dragon Legend',
    'class'        => 4,
    'image'        => 'images/cruises/dragon-legend.jpg',
    'gallery'      => ['images/cruises/dragon-legend.jpg'],
    'desc_vi'      => 'Du thuyền chuyên khai thác tuyến Vịnh Bái Tử Long yên tĩnh, ít đông đúc. Không gian gần gũi thiên nhiên, dịch vụ thân thiện và phong cảnh hoang sơ chưa bị thương mại hóa.',
    'desc_en'      => 'A cruise exploring the tranquil Bai Tu Long Bay, less crowded and commercialized. Intimate atmosphere, friendly service and pristine natural scenery.',
    'long_desc_vi' => 'Dragon Legend thuộc Indochina Junk, chuyên khai thác tuyến Vịnh Bái Tử Long — vùng biển yên tĩnh và hoang sơ hơn so với vịnh Hạ Long chính. Với 24 cabin phong cách Đông Dương cổ điển, tàu mang đến không gian gần gũi và ấm cúng. Hành trình đưa du khách đến hang Thiên Cảnh Sơn với những nhũ đá triệu năm, làng chài Vũng Viêng nổi trên mặt nước, bãi tắm Ban Chan hoang sơ, và trải nghiệm chèo kayak qua những hẻm đá vôi kỳ vĩ. Đây là lựa chọn lý tưởng cho du khách muốn tránh xa đám đông và tận hưởng thiên nhiên nguyên bản.',
    'long_desc_en' => 'Dragon Legend by Indochina Junk specializes in Bai Tu Long Bay — a quieter and more pristine area compared to the main Ha Long Bay. With 24 Indochina-style cabins, the vessel offers an intimate and cozy atmosphere. The itinerary takes guests to Thien Canh Son Cave with million-year-old stalactites, Vung Vieng floating fishing village, pristine Ban Chan beach, and kayaking through majestic limestone gorges. This is the ideal choice for travelers seeking to escape the crowds and enjoy unspoiled nature.',
    'price_from'   => '1.800.000',
    'cabin_count'  => 24,
    'year_launched' => 2014,
    'route_vi'     => 'Vịnh Bái Tử Long',
    'route_en'     => 'Bai Tu Long Bay',
    'highlights'   => ['Vịnh Bái Tử Long', 'Hang Thiên Cảnh Sơn', 'Làng chài Vũng Viêng', 'Thuyền tre', 'Nấu ăn', 'Bãi tắm hoang sơ', 'Kayak'],
    'highlights_en' => ['Bai Tu Long Bay', 'Thien Canh Son Cave', 'Vung Vieng village', 'Bamboo boat', 'Cooking class', 'Pristine beach', 'Kayaking'],
    'rating'       => 4.5,
    'reviews'      => 980,
    'color'        => '#0D9488',
    'itinerary_vi' => [
      'day1' => [
        'title' => 'Ngày 1: Bái Tử Long — Hang Thiên Cảnh Sơn',
        'items' => [
          '12:00 — Nhận phòng tại Hòn Gai, welcome drink',
          '12:30 — Ăn trưa hải sản tươi',
          '14:30 — Tham quan hang Thiên Cảnh Sơn',
          '16:00 — Chèo kayak qua hẻm đá vôi',
          '17:00 — Tắm biển bãi Ban Chan',
          '18:00 — Trình diễn nấu ăn trên sundeck',
          '19:30 — Dinner hải sản BBQ',
          '21:00 — Câu mực đêm, trò chuyện quanh tàu',
        ],
      ],
      'day2' => [
        'title' => 'Ngày 2: Làng chài Vũng Viêng — Trở về',
        'items' => [
          '06:30 — Tai Chi buổi sáng',
          '07:00 — Ăn sáng',
          '08:00 — Thuyền tre thăm làng chài Vũng Viêng',
          '09:30 — Trả phòng',
          '10:00 — Brunch nhẹ',
          '11:00 — Cập bến Hòn Gai',
        ],
      ],
    ],
    'itinerary_en' => [
      'day1' => [
        'title' => 'Day 1: Bai Tu Long — Thien Canh Son Cave',
        'items' => [
          '12:00 PM — Check-in at Hon Gai, welcome drink',
          '12:30 PM — Fresh seafood lunch',
          '2:30 PM — Visit Thien Canh Son Cave',
          '4:00 PM — Kayaking through limestone gorges',
          '5:00 PM — Swimming at Ban Chan beach',
          '6:00 PM — Cooking demonstration on sundeck',
          '7:30 PM — Seafood BBQ dinner',
          '9:00 PM — Night squid fishing, socializing onboard',
        ],
      ],
      'day2' => [
        'title' => 'Day 2: Vung Vieng Village — Return',
        'items' => [
          '6:30 AM — Morning Tai Chi',
          '7:00 AM — Breakfast',
          '8:00 AM — Bamboo boat to Vung Vieng fishing village',
          '9:30 AM — Check out',
          '10:00 AM — Light brunch',
          '11:00 AM — Disembark at Hon Gai',
        ],
      ],
    ],
    'cabins_vi' => [
      ['name' => 'Deluxe Cabin', 'size' => '18m²', 'bed' => 'Giường đôi / 2 giường đơn', 'price' => '1.800.000', 'desc' => 'Cabin ấm cúng phong cách Đông Dương'],
      ['name' => 'Premium Cabin', 'size' => '22m²', 'bed' => 'Giường đôi', 'price' => '2.500.000', 'desc' => 'Cabin rộng hơn, cửa sổ lớn view biển'],
      ['name' => 'Dragon Suite', 'size' => '32m²', 'bed' => 'Giường King', 'price' => '3.500.000', 'desc' => 'Suite ban công riêng, trang trí Đông Dương tinh tế'],
    ],
    'cabins_en' => [
      ['name' => 'Deluxe Cabin', 'size' => '18m²', 'bed' => 'Double / Twin beds', 'price' => '1,800,000', 'desc' => 'Cozy Indochina-style cabin'],
      ['name' => 'Premium Cabin', 'size' => '22m²', 'bed' => 'Double bed', 'price' => '2,500,000', 'desc' => 'Larger cabin with big windows and sea view'],
      ['name' => 'Dragon Suite', 'size' => '32m²', 'bed' => 'King bed', 'price' => '3,500,000', 'desc' => 'Suite with private balcony and refined Indochina decor'],
    ],
    'amenities' => ['Wi-Fi', 'Sundeck', 'Nhà hàng', 'Bar', 'Thuyền tre', 'Kayak'],
    'amenities_en' => ['Wi-Fi', 'Sundeck', 'Restaurant', 'Bar', 'Bamboo boat', 'Kayak'],
  ],

  'la-regina' => [
    'id'           => 'la-regina',
    'name'         => 'La Regina Legend',
    'class'        => 5,
    'image'        => 'images/cruises/la-regina.jpg',
    'gallery'      => ['images/cruises/la-regina.jpg'],
    'desc_vi'      => 'Du thuyền 5 sao phong cách cổ điển với tông gỗ ấm áp và chi tiết đồng thau tinh xảo. Sở hữu cabin siêu rộng từ 45m², hành trình khám phá vịnh Lan Hạ tuyệt đẹp.',
    'desc_en'      => 'A classic-style 5-star cruise with warm wood tones and refined brass details. Features spacious cabins from 45m², exploring the stunning Lan Ha Bay.',
    'long_desc_vi' => 'La Regina Legend là du thuyền 5 sao ra mắt năm 2018, gây ấn tượng bởi phong cách thiết kế cổ điển sang trọng với tông gỗ ấm áp và chi tiết đồng thau tinh xảo. Điểm nổi bật nhất là các cabin siêu rộng từ 45m² — lớn hơn nhiều so với tiêu chuẩn ngành du thuyền. Hành trình đưa du khách khám phá vịnh Lan Hạ với hang Sáng Tối, hang Trung Trang, làng chài Việt Hải, và bãi biển Ba Trái Đào tuyệt đẹp. Lớp nấu ăn trên sundeck cùng bếp trưởng tàu là trải nghiệm không thể bỏ lỡ.',
    'long_desc_en' => 'La Regina Legend is a 5-star cruise launched in 2018, impressing with its classic luxury design featuring warm wood tones and refined brass details. The standout feature is the super-spacious cabins from 45m² — much larger than the cruise industry standard. The itinerary takes guests through Lan Ha Bay with Dark & Bright Cave, Trung Trang Cave, Viet Hai fishing village, and the beautiful Ba Trai Dao beach. The cooking class on the sundeck with the ship chef is an unmissable experience.',
    'price_from'   => '3.200.000',
    'cabin_count'  => 20,
    'year_launched' => 2018,
    'route_vi'     => 'Vịnh Lan Hạ',
    'route_en'     => 'Lan Ha Bay',
    'highlights'   => ['Cabin 45m²', 'Vịnh Lan Hạ', 'Lớp nấu ăn', 'Jacuzzi & Spa', 'Bãi Ba Trái Đào', 'Hang Trung Trang', 'Làng Việt Hải'],
    'highlights_en' => ['45m² cabin', 'Lan Ha Bay', 'Cooking class', 'Jacuzzi & Spa', 'Ba Trai Dao beach', 'Trung Trang Cave', 'Viet Hai village'],
    'rating'       => 4.7,
    'reviews'      => 650,
    'color'        => '#B45309',
    'itinerary_vi' => [
      'day1' => [
        'title' => 'Ngày 1: Vịnh Lan Hạ — Hang Sáng Tối — Bãi Ba Trái Đào',
        'items' => [
          '11:30 — Nhận phòng tại bến Gót, welcome drink',
          '12:00 — Ăn trưa trên tàu khi ngắm cảnh Lan Hạ',
          '14:00 — Thuyền tre khám phá hang Sáng Tối',
          '15:30 — Tắm biển bãi Ba Trái Đào',
          '16:30 — Chèo kayak quanh các hòn đảo đá vôi',
          '17:30 — Lớp nấu ăn trên sundeck',
          '19:00 — Dinner cổ điển phong cách Pháp — Việt',
          '21:00 — Câu mực đêm, thư giãn jacuzzi',
        ],
      ],
      'day2' => [
        'title' => 'Ngày 2: Hang Trung Trang — Trở về',
        'items' => [
          '06:30 — Tai Chi buổi sáng',
          '07:00 — Ăn sáng buffet',
          '08:00 — Tham quan hang Trung Trang trên đảo Cát Bà',
          '09:30 — Trả phòng',
          '10:00 — Brunch, ngắm vịnh Lan Hạ',
          '11:30 — Cập bến',
        ],
      ],
    ],
    'itinerary_en' => [
      'day1' => [
        'title' => 'Day 1: Lan Ha Bay — Dark & Bright Cave — Ba Trai Dao',
        'items' => [
          '11:30 AM — Check-in at Got pier, welcome drink',
          '12:00 PM — Lunch onboard while cruising Lan Ha Bay',
          '2:00 PM — Bamboo boat through Dark & Bright Cave',
          '3:30 PM — Swimming at Ba Trai Dao beach',
          '4:30 PM — Kayaking around limestone islands',
          '5:30 PM — Cooking class on the sundeck',
          '7:00 PM — Classic French-Vietnamese dinner',
          '9:00 PM — Night squid fishing, jacuzzi relaxation',
        ],
      ],
      'day2' => [
        'title' => 'Day 2: Trung Trang Cave — Return',
        'items' => [
          '6:30 AM — Morning Tai Chi',
          '7:00 AM — Breakfast buffet',
          '8:00 AM — Visit Trung Trang Cave on Cat Ba Island',
          '9:30 AM — Check out',
          '10:00 AM — Brunch, Lan Ha Bay views',
          '11:30 AM — Disembark',
        ],
      ],
    ],
    'cabins_vi' => [
      ['name' => 'Junior Suite', 'size' => '45m²', 'bed' => 'Giường King', 'price' => '3.200.000', 'desc' => 'Suite rộng rãi phong cách cổ điển, ban công riêng'],
      ['name' => 'Senior Suite', 'size' => '50m²', 'bed' => 'Giường King', 'price' => '4.500.000', 'desc' => 'Suite cao cấp, bồn tắm view biển, nội thất gỗ quý'],
      ['name' => 'Royal Suite', 'size' => '60m²', 'bed' => 'Giường King', 'price' => '6.200.000', 'desc' => 'Suite hoàng gia, sân thượng riêng, butler cá nhân'],
    ],
    'cabins_en' => [
      ['name' => 'Junior Suite', 'size' => '45m²', 'bed' => 'King bed', 'price' => '3,200,000', 'desc' => 'Spacious classic-style suite with private balcony'],
      ['name' => 'Senior Suite', 'size' => '50m²', 'bed' => 'King bed', 'price' => '4,500,000', 'desc' => 'Premium suite with sea-view bathtub and precious wood decor'],
      ['name' => 'Royal Suite', 'size' => '60m²', 'bed' => 'King bed', 'price' => '6,200,000', 'desc' => 'Royal suite with private terrace and personal butler'],
    ],
    'amenities' => ['Wi-Fi', 'Jacuzzi', 'Spa', 'Nhà hàng', 'Bar', 'Sundeck', 'Phòng Gym', 'Thư viện'],
    'amenities_en' => ['Wi-Fi', 'Jacuzzi', 'Spa', 'Restaurant', 'Bar', 'Sundeck', 'Gym', 'Library'],
  ],
];
