<?php

/**
 * Ha Long Bay Tourism Services / Tickets Data
 * Sun World Ha Long Complex - Updated 2025/2026
 */

$services_data = [
    'queen-cable-car' => [
        'name_vi' => 'Cáp Treo Nữ Hoàng',
        'name_en' => 'Queen Cable Car',
        'desc_vi' => 'Hệ thống cáp treo 2 tầng đầu tiên tại Việt Nam với 99 cabin hiện đại, đưa du khách bay trên Vịnh Hạ Long ở độ cao gần 200m. Trải nghiệm ngắm toàn cảnh vịnh từ trên cao tuyệt đẹp.',
        'desc_en' => 'Vietnam\'s first dual-story cable car system with 99 modern cabins, taking visitors across Ha Long Bay at nearly 200m height. Experience stunning panoramic views of the bay from above.',
        'price_adult' => '380.000',
        'price_child' => '280.000',
        'price_adult_raw' => 380000,
        'price_child_raw' => 280000,
        'image' => 'images/services/queen-cable-car.jpg',
        'icon' => 'bi-wind',
        'highlights_vi' => ['Cáp treo 2 tầng đầu tiên VN', 'Ngắm toàn cảnh Vịnh Hạ Long', '99 cabin hiện đại', 'Độ cao gần 200m'],
        'highlights_en' => ['First dual-story cable car in VN', 'Panoramic Ha Long Bay views', '99 modern cabins', 'Nearly 200m height'],
        'category_vi' => 'Ngắm cảnh',
        'category_en' => 'Sightseeing',
        'rating' => 4.8,
        'reviews' => 2450,
    ],
    'dragon-park' => [
        'name_vi' => 'Công Viên Rồng Dragon Park',
        'name_en' => 'Dragon Park',
        'desc_vi' => 'Công viên giải trí hàng đầu với hơn 20 trò chơi cảm giác mạnh đẳng cấp quốc tế. Trải nghiệm Dragon\'s Run, Rhino Sling, Monster Spin và nhiều trò chơi đỉnh cao khác.',
        'desc_en' => 'A leading amusement park with over 20 world-class thrilling rides. Experience Dragon\'s Run, Rhino Sling, Monster Spin and many more top-tier attractions.',
        'price_adult' => '300.000',
        'price_child' => '200.000',
        'price_adult_raw' => 300000,
        'price_child_raw' => 200000,
        'image' => 'images/services/dragon-park.png',
        'icon' => 'bi-hurricane',
        'highlights_vi' => ['20+ trò chơi cảm giác mạnh', 'Dragon\'s Run tốc độ cao', 'Phù hợp mọi lứa tuổi', 'Đẳng cấp quốc tế'],
        'highlights_en' => ['20+ thrilling rides', 'High-speed Dragon\'s Run', 'Suitable for all ages', 'World-class standard'],
        'category_vi' => 'Giải trí',
        'category_en' => 'Entertainment',
        'rating' => 4.7,
        'reviews' => 3120,
    ],
    'typhoon-water-park' => [
        'name_vi' => 'Công Viên Nước Typhoon',
        'name_en' => 'Typhoon Water Park',
        'desc_vi' => 'Thiên đường nước nhiệt đới với 12 trò chơi nước độc đáo. Trượt nước Thunder Falls, hồ bơi tạo sóng Tsunami Spillway, Sun Pool và Magical Cove mang đến trải nghiệm mát lạnh sảng khoái.',
        'desc_en' => 'A tropical water paradise with 12 unique water attractions. Thunder Falls water slides, Tsunami Spillway wave pool, Sun Pool and Magical Cove deliver refreshing cool experiences.',
        'price_adult' => '350.000',
        'price_child' => '250.000',
        'price_adult_raw' => 350000,
        'price_child_raw' => 250000,
        'image' => 'images/services/typhoon-water-park.jpg',
        'icon' => 'bi-water',
        'highlights_vi' => ['12 trò chơi nước độc đáo', 'Hồ tạo sóng nhân tạo', 'Trượt nước xoắn ốc', 'Khu vui chơi trẻ em'],
        'highlights_en' => ['12 unique water rides', 'Artificial wave pool', 'Spiral water slides', 'Kids play area'],
        'category_vi' => 'Công viên nước',
        'category_en' => 'Water Park',
        'rating' => 4.6,
        'reviews' => 1890,
    ],
    'mystic-hill' => [
        'name_vi' => 'Đồi Bí Ẩn & Sun Wheel',
        'name_en' => 'Mystic Hill & Sun Wheel',
        'desc_vi' => 'Khám phá Đồi Bí Ẩn với vòng quay Sun Wheel cao 215m - biểu tượng của Sun World Hạ Long. Bao gồm Game World, khu vui chơi trẻ em Kidoland và Vườn Nhật Bản yên bình.',
        'desc_en' => 'Explore Mystic Hill with the 215m Sun Wheel - the iconic symbol of Sun World Ha Long. Includes Game World, Kidoland children\'s area and the serene Japanese Garden.',
        'price_adult' => '380.000',
        'price_child' => '280.000',
        'price_adult_raw' => 380000,
        'price_child_raw' => 280000,
        'image' => 'images/services/sun-wheel.jpg',
        'icon' => 'bi-ferris-wheel',
        'highlights_vi' => ['Sun Wheel cao 215m', 'Vườn Nhật Bản', 'Game World & Kidoland', 'View toàn cảnh Hạ Long'],
        'highlights_en' => ['215m Sun Wheel', 'Japanese Garden', 'Game World & Kidoland', 'Panoramic Ha Long view'],
        'category_vi' => 'Khám phá',
        'category_en' => 'Explore',
        'rating' => 4.7,
        'reviews' => 2100,
    ],
    'combo-2-parks' => [
        'name_vi' => 'Combo 2 Công Viên',
        'name_en' => '2-Park Combo',
        'desc_vi' => 'Tiết kiệm hơn khi kết hợp 2 công viên trong cùng một ngày. Tự do lựa chọn giữa Cáp treo Nữ Hoàng, Dragon Park hoặc Typhoon Water Park theo sở thích.',
        'desc_en' => 'Save more by combining 2 parks in one day. Freely choose between Queen Cable Car, Dragon Park or Typhoon Water Park based on your preference.',
        'price_adult' => '500.000',
        'price_child' => '380.000',
        'price_adult_raw' => 500000,
        'price_child_raw' => 380000,
        'image' => 'images/services/cable-car-overview.jpg',
        'icon' => 'bi-ticket-perforated',
        'highlights_vi' => ['Tự chọn 2 công viên', 'Tiết kiệm đến 30%', 'Sử dụng trong ngày', 'Linh hoạt lựa chọn'],
        'highlights_en' => ['Choose any 2 parks', 'Save up to 30%', 'Valid for 1 day', 'Flexible choices'],
        'category_vi' => 'Combo tiết kiệm',
        'category_en' => 'Value Combo',
        'rating' => 4.9,
        'reviews' => 4200,
        'is_combo' => true,
    ],
    'combo-3-parks' => [
        'name_vi' => 'Combo 3 Công Viên',
        'name_en' => '3-Park Combo',
        'desc_vi' => 'Trọn bộ trải nghiệm Sun World Hạ Long! Combo bao gồm cả 3 công viên: Cáp treo Nữ Hoàng, Dragon Park và Typhoon Water Park, sử dụng trong 2 ngày liên tiếp.',
        'desc_en' => 'The complete Sun World Ha Long experience! Combo includes all 3 parks: Queen Cable Car, Dragon Park and Typhoon Water Park, valid for 2 consecutive days.',
        'price_adult' => '600.000',
        'price_child' => '450.000',
        'price_adult_raw' => 600000,
        'price_child_raw' => 450000,
        'image' => 'images/services/typhoon-water-park.jpg',
        'icon' => 'bi-stars',
        'highlights_vi' => ['Trọn bộ 3 công viên', 'Sử dụng 2 ngày liên tiếp', 'Tiết kiệm đến 40%', 'Trải nghiệm đầy đủ nhất'],
        'highlights_en' => ['All 3 parks included', 'Valid for 2 consecutive days', 'Save up to 40%', 'Most complete experience'],
        'category_vi' => 'Combo VIP',
        'category_en' => 'VIP Combo',
        'rating' => 4.9,
        'reviews' => 3650,
        'is_combo' => true,
    ],
];
